### ISSUE TITLE
Unable to replace prop for 'these buildings' when 'all buildings' already applied

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/BOB#37] opened 2021-12-26 04:13 UTC
I've made a global replacement of `[v] Wall Light White` with `Pipeline Mounted Light` - including setting angle, etc. Now my city has nice orange mood lighting everywhere instead of harsh white floodlights.

However, for some reason the light is buried on the Natural Disasters `Earthquake Early Warning Sensor` building:

![image](https://user-images.githubusercontent.com/1386719/147398609-51ab66c6-d75c-40ba-9960-472cbd1f1b6b.png)

So I'm trying to set a building-specific override to change the Y offset for that building (ie. keep same light, rotation, etc., just lift it up out of ground). I can set the Y offset and click `These Buildings` button, but nothing changes on the map.

Before change:

![image](https://user-images.githubusercontent.com/1386719/147398663-620bc6fc-a2c6-413b-afcf-d5c96630fe8c.png)

After change (the icon in list on right is now single building so it seems the override is present, but no change on map):

![image](https://user-images.githubusercontent.com/1386719/147398672-eafa3d5a-bf69-40a1-8652-7fb83447a865.png)

EDIT: Merry xmas (:

**Comment by algernon-A** [comment] 2021-12-28 01:00
Confirmed.  Issue is due to a mismatch between m_fixedHeight flags between original and replacement.

**Comment by algernon-A** [comment] 2022-01-07 00:25
Fixed in 4b2590e794c0f100cecba1b26a0ad4266c82bead

**Closed as completed by algernon-A** 2022-01-07 00:25 UTC
Labels: bug
